### ISSUE TITLE
Ajouter deux lignes de tampons à la grille

### ISSUE THREAD

**Issue by karimElmougi** [karimElmougi/Tetris232#5]
Deux lignes au dessus de la grille qui ne sont jamais dessinnées et qui servent à spawner les tetrominos. Elles pourront également servir pour détecter un game over.  Une fonction qui retourne le SpaceNode de préférence pour le spawn serait utile, dans SpaceGrid

**Comment by mathlizee** [comment]
Done. Ajout de 4 lignes plutôt que 2 (facilement modifiable dans le code)
